### ISSUE TITLE
AppFooter rendering ul without li

### ISSUE THREAD

**Issue by alexanderflink** [noaignite/create-ignite-app#39]
https://github.com/noaignite/create-ignite-app/blob/dc2e7eb00f9ea854674bfddac3ddbb051d624fda/src/containers/App/partials/AppFooter.js#L50

Noticed that AppFooter renders an `<ul>` with only `<a>` elements in it. The links should probably be wrapped in `<li>` elements.

**Comment by maeertin** [comment]
Thanks @alexanderflink, I simplified the markup for the links and it's now correct :)
