### ISSUE TITLE
[Storybook] Crashes with `next@12.2.0`

### ISSUE THREAD

**Issue by vincentboiardt** [noaignite/create-ignite-app#66]
1. `yarn add next`
1. `yarn && yarn storybook`

Shows the following error

      ERROR in ./node_modules/next/dist/shared/lib/router/router.js 37:8
      Module parse failed: Unexpected token (37:8)
      You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
      | class Router {
      |     // Server Data Cache
      >     sdc = {};
      |     isFirstPopStateEvent = true;
      |     _key = createKey();
       @ ./node_modules/next/dist/client/router.js 22:37-75
       @ ./node_modules/next/router.js
       @ ./src/layouts/AppBase/partials/AppBaseLoader.js
       @ ./src/layouts/AppBase/partials/index.js
       @ ./src/layouts/AppBase/AppBase.js
       @ ./src/layouts/AppBase/stories.js
       @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?stories\.js)$
       @ ./generated-stories-entry.js
       @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-a11y/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

**Comment by maeertin** [comment]
No longer an issue in the latest next build (v12.2.3 at time of writing).
