### ISSUE TITLE
Look into using NextJS new localFont loader

### ISSUE THREAD

**Issue by maeertin** [noaignite/create-ignite-app#76]
https://nextjs.org/docs/basic-features/font-optimization#local-fonts

**Comment by alexanderflink** [comment]
Let's see if this inlines the fonts and if it performs better

**Comment by janmysiak** [comment]
Just tried it and looks like this requires SWC:

`Syntax error: "@next/font" requires SWC although Babel is being used due to a custom babel config being present.
Read more: https://nextjs.org/docs/messages/babel-font-loader-conflict`

**Comment by alexanderflink** [comment]
This is a great reason to go to SWC!

**Comment by maeertin** [comment]
Closing PR as no longer relevant as "cia" is now purely a documentation app.
