### ISSUE TITLE
[Unsplash] Replace mocked images to other service

### ISSUE THREAD

**Issue by adamsoderstrom** [noaignite/create-ignite-app#80]
We're currently using Unsplash's `source.unsplash` service, which seems to be phased out from the Unsplash platform.

I've experienced that these URL's has increased in response times + resolves to a `503 (Service Unavailable)`. 

Maybe we could switch to an equivalent service? Maybe even [`api.unsplash.com`](https://unsplash.com/developers)?

https://github.com/noaignite/create-ignite-app/blob/4e12552acf8375887266e0b998258ebb0bd6fbc0/src/api/__mock__/centra/products.js#L42

**Comment by manik-dhanjal** [comment]
Hi,
I would like to contribute to fixing this bug, can you please guide me to set it up on my machine?

**Comment by maeertin** [comment]
Closing PR as no longer relevant as "cia" is now purely a documentation app.
