### ISSUE TITLE
Update RegEx in RouterLink for www

### ISSUE THREAD

**Issue by axelpahne** [noaignite/create-ignite-app#86]
In the RouterLink component... 
The current RegEx does not have support for www so it does not set thoes links as external

```
  // Render as a regular `a` tag if external link.
  if (external || /^https?:\/\//.test(href)) {
    return (
      <a href={href} rel="noopener noreferrer" target="_blank" ref={ref} {...other}>
        {children}
      </a>
    )
  }
```

**Comment by maeertin** [comment]
Thank you @axelpahne for the issue ✨ What's your thoughts here @alexanderflink?

**Comment by alexanderflink** [comment]
Apparently, `<a>` tags in HTML that do not have protocol (e.g www.google.com) are actually interpreted as relative links by the browser. So we should not fix this as it is expected behaviour. We could possibly add validation in the cms that adds the protocol if the user enters "www".
